language: java
jdk:
 - oraclejdk8
script:
  - mvn install
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "target/Installer-1.0.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
